name: darts release workflow

on:
  workflow_dispatch:
    inputs:
        bump_type:
          description: "Bump type (#major, #minor, #patch)"
          required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "1. Clone repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'

      - name: "2. Set up Python 3.6"
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: "3. Update pip"
        run: |
          python -m pip install --upgrade pip

      - name: "4. Attach cache for pip"
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cache/pip
          key: release-${{ runner.os }}-pip-${{ hashFiles('requirements/release.txt') }}
          restore-keys: |
            release-${{ runner.os }}-pip-

      - name: "5. Install release dependencies"
        run: |
          pip install -q -r requirements/release.txt

      - name: "6. Determine next version"
        uses: LeoTafti/github-tag-action@master
        id: bump_dry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
          BUMP_TYPE: ${{ github.event.inputs.bump_type}}

      - name: "7. Bump version"
        run: |
          bump2version --new-version ${{ steps.bump_dry.outputs.new_tag }} patch

      - name: "8. Commit new version"
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Release ${{ steps.bump_dry.outputs.new_tag }}
          branch: master
          commit_user_name: Unit8 Bot
          commit_user_email: info@unit8.co
